### ISSUE TITLE
多签交易返回Validate signature error: Permission denied

### ISSUE THREAD

**Issue by lis-ylfy** [Aiden-777/EasyTron#5]
java.lang.RuntimeException: OTHER_ERROR, <ByteString@2d04cac size=43 contents="Validate signature error: Permission denied">
	at org.tron.trident.core.ApiWrapper.broadcastTransaction(ApiWrapper.java:435)
	at com.repaid.common.tron.service.TronTransferServer.multiSignature(TronTransferServer.java:316)
	at com.repaid.modules.system.controller.SysTronTestController.multiSignature(SysTronTestController.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:903)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:809)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)

**Comment by Aiden-777** [comment]
活跃权限的话确保ID正确、权限阈值达标。

**Comment by lis-ylfy** [comment]
是我把活跃权限的几个地址，owenr权限也授权了，导致活跃权限不能用，只能使用owenr权限，已经解决了，其它示例我也使用了，都没问题。万分感觉老哥。老哥大义！




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Aiden-777/EasyTron"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月12日(星期四) 中午1:05
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Aiden-777/EasyTron] 多签交易返回Validate signature error: Permission denied (Issue #5)





 
活跃权限的话确保ID正确、权限阈值达标。
